CREATE DATABASE IF NOT EXISTS car_booking_system CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE car_booking_system;

CREATE TABLE admins (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(190) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE vehicles (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(180) NOT NULL,
    slug VARCHAR(190) NOT NULL UNIQUE,
    capacity VARCHAR(60) NOT NULL,
    type VARCHAR(100) NOT NULL,
    accent VARCHAR(120) DEFAULT NULL,
    summary TEXT NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    highlights JSON DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE reviews (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    category ENUM('google', 'domestic', 'local', 'international') NOT NULL DEFAULT 'google',
    type ENUM('text', 'video') NOT NULL DEFAULT 'text',
    title VARCHAR(190) NOT NULL,
    customer_name VARCHAR(150) NOT NULL,
    traveler_from VARCHAR(150) DEFAULT NULL,
    route VARCHAR(190) DEFAULT NULL,
    review_date DATE DEFAULT NULL,
    rating TINYINT UNSIGNED NOT NULL DEFAULT 5,
    content TEXT NOT NULL,
    media_url VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE gallery_items (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(180) NOT NULL,
    media_type ENUM('image', 'video') NOT NULL DEFAULT 'image',
    media_url VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE destinations (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    route VARCHAR(190) NOT NULL,
    tag VARCHAR(120) DEFAULT NULL,
    summary TEXT NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE bookings (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    customer_name VARCHAR(150) NOT NULL,
    phone VARCHAR(40) NOT NULL,
    from_location VARCHAR(190) NOT NULL,
    to_destination VARCHAR(190) NOT NULL,
    pickup_date DATE NOT NULL,
    pickup_time TIME DEFAULT NULL,
    return_date DATE DEFAULT NULL,
    vehicle_name VARCHAR(180) DEFAULT NULL,
    context VARCHAR(120) DEFAULT NULL,
    status ENUM('pending', 'confirmed', 'cancelled') NOT NULL DEFAULT 'pending',
    status_updated_at TIMESTAMP NULL DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE partner_leads (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(190) NOT NULL,
    phone VARCHAR(40) NOT NULL,
    city VARCHAR(150) NOT NULL,
    company VARCHAR(150) DEFAULT NULL,
    category VARCHAR(120) NOT NULL,
    comments TEXT DEFAULT NULL,
    status ENUM('new', 'contacted', 'qualified', 'closed') NOT NULL DEFAULT 'new',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
